import os
import datetime
from dotenv import load_dotenv

# Alpaca API
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.enums import DataFeed

import agent
import notifier

# Load environment variables
load_dotenv()

API_KEY = os.getenv("ALPACA_API_KEY")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")
PAPER = os.getenv("ALPACA_PAPER", "True") == "True"

if not API_KEY or not SECRET_KEY:
    print("Error: Missing Alpaca API keys in .env file.")
    exit(1)

# Initialize Alpaca Clients
trading_client = TradingClient(API_KEY, SECRET_KEY, paper=PAPER)
data_client = StockHistoricalDataClient(API_KEY, SECRET_KEY)

def fetch_portfolio_state():
    print("Fetching portfolio state...")
    account = trading_client.get_account()
    cash = float(account.cash)
    
    positions = trading_client.get_all_positions()
    portfolio_positions = []
    last_prices = {}
    
    for pos in positions:
        ticker = pos.symbol
        qty = float(pos.qty)
        price = float(pos.current_price)
        portfolio_positions.append({
            'ticker': ticker,
            'quantity': qty,
            'avg_entry': float(pos.avg_entry_price)
        })
        last_prices[ticker] = price

    portfolio_state = {
        'positions': portfolio_positions,
        'last_prices': last_prices
    }
    
    print(f"Current Cash: ${cash:,.2f}")
    print(f"Current Positions: {[p['ticker'] for p in portfolio_positions]}")
    return portfolio_state, cash

def fetch_market_state(universe, last_prices):
    print(f"Fetching historical market data for universe of {len(universe)} symbols...")
    # Fetch ~300 calendar days. 
    # Subtract 20 minutes from now to ensure we don't request real-time SIP data which requires a paid tier
    end_date = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(minutes=20)
    start_date = end_date - datetime.timedelta(days=300)
    
    request_params = StockBarsRequest(
        symbol_or_symbols=universe,
        timeframe=TimeFrame.Day,
        start=start_date,
        end=end_date,
        feed=DataFeed.IEX
    )
    
    bars = data_client.get_stock_bars(request_params)
    
    market_state = {}
    for ticker in universe:
        market_state[ticker] = []
        if ticker in bars.data:
            for bar in bars.data[ticker]:
                market_state[ticker].append({
                    'date': str(bar.timestamp.date()),
                    'open': float(bar.open),
                    'high': float(bar.high),
                    'low': float(bar.low),
                    'close': float(bar.close),
                    'volume': float(bar.volume)
                })
        
        # Ensure the last live price from the portfolio is the very last close price in the state
        # so the agent acts on the absolute latest real-time data instead of yesterday's close
        if ticker in last_prices and len(market_state[ticker]) > 0:
            market_state[ticker].append({
                'date': str(end_date.date()),
                'open': last_prices[ticker],
                'high': last_prices[ticker],
                'low': last_prices[ticker],
                'close': last_prices[ticker],
                'volume': 0
            })

    return market_state

def execute_orders(orders):
    if not orders:
        print("No orders generated by agent. Doing nothing.")
        return

    print(f"Agent generated {len(orders)} orders.")
    for order in orders:
        ticker = order['ticker']
        side = order['side']
        qty = int(order['quantity'])
        
        if qty <= 0:
            continue
            
        print(f"Executing {side.upper()} order for {qty} shares of {ticker}...")
        
        try:
            req = MarketOrderRequest(
                symbol=ticker,
                qty=qty,
                side=OrderSide.BUY if side == 'buy' else OrderSide.SELL,
                time_in_force=TimeInForce.GTC,
                extended_hours=True
            )
            trading_client.submit_order(order_data=req)
            print(f"Successfully submitted {side.upper()} for {ticker}.")
            
            # Send Discord webhook push notification
            # We don't have the exact fill price synchronously, so we pass a placeholder or estimate
            # For a more robust system, we would listen to Alpaca trade webhooks.
            notifier.send_discord_alert(side, ticker, qty, 0.0) 
            
        except Exception as e:
            print(f"Failed to submit order for {ticker}: {e}")

if __name__ == "__main__":
    print("=== TradeVision V3 Live Executor ===")
    
    portfolio_state, cash = fetch_portfolio_state()
    full_universe = set(agent.UNIVERSE + [p['ticker'] for p in portfolio_state['positions']])
    
    try:
        from alpaca.data.historical import StockHistoricalDataClient
        from alpaca.data.requests import StockLatestQuoteRequest
        # Also need to add feed='iex' or similar for quotes if possible, 
        # but let's just use the fallback if it fails
        quote_req = StockLatestQuoteRequest(symbol_or_symbols=list(full_universe))
        quotes = data_client.get_stock_latest_quote(quote_req)
        for sym, quote in quotes.items():
            portfolio_state['last_prices'][sym] = float(quote.ask_price)
    except Exception as e:
        print(f"Warning: Could not fetch latest quotes (free tier limits may apply). Fallback to last close. {e}")

    market_state = fetch_market_state(list(full_universe), portfolio_state['last_prices'])
    
    print("Feeding data to TradeVision Agent...")
    
    agent._state['peak_equity'] = cash + sum(p['quantity'] * portfolio_state['last_prices'].get(p['ticker'], 0) for p in portfolio_state['positions'])
    agent._state['last_rebal_day'] = -999  # Force a rebalance on first run
    
    orders = agent.decide(market_state, portfolio_state, cash)
    execute_orders(orders)
    print("Execution sequence complete.")
